spring:
  profiles: dev
  application :
    name: mall-share-service
  jackson:
    serialization:
      write-dates-as-timestamps: true
    #date-format: yyyy-MM-dd HH:mm:ss
    #time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-boot?serverTimezone=UTC&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    druid:
       filters: stat
       max-active: 20
       initial-size: 5
       max-wait: 60000
       min-idle: 1
       time-between-eviction-runs-millis: 60000
       min-evictable-idle-time-millis: 300000
       validation-query: select 1
       test-while-idle: true
       test-on-borrow: true
       test-on-return: true
       pool-prepared-statements: true
       max-open-prepared-statements: 20
  data:
    mongodb:
      uri: mongodb://172.17.250.111:27017/mall-promo

logging:
 level:
  root: INFO
  org.springframework: INFO
  org.mybatis: WARN
  com.jianke.mall: INFO



springfox.documentation.swagger.v2.path: /api-docs