server:
  port: 8080
spring:
  profiles:
    active: dev
---
spring:
  profiles: default
  application :
    name: mall-share-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.24.30.6:3306/mall_product?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: jianke@test123
    druid:
       filters: stat
       max-active: 20
       initial-size: 5
       max-wait: 60000
       min-idle: 1
       time-between-eviction-runs-millis: 60000
       min-evictable-idle-time-millis: 300000
       validation-query: select 1
       test-while-idle: true
       test-on-borrow: true
       test-on-return: true
       pool-prepared-statements: true
       max-open-prepared-statements: 20


logging:
 level:
  root: INFO
  org.springframework: INFO
  org.mybatis: WARN
  com.jianke.mall: INFO

